spring.application.name=squaredeal

server.port=8080


spring.datasource.url=jdbc:mysql://localhost:3306/squaredeal?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Schaubey063@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret-key=MyVeryLongSecretKeyForJwtAuthenticationSystem123456789
jwt.expiration-time=36000000

